name: RainbowNametags
version: 1.0
main: com.solexgames.rainbow.NameTagPlugin

commands:
  nametag:
    aliases: ["rainbow", "rainbownametags"]
    description: Toggles the rainbow nametag above your head and in tab!
